### ISSUE TITLE
ARM projects stop compiling when adding "Connected Service" -> "IoT Hub"

### ISSUE THREAD

**Issue by TechPreacher** [Azure/azure-iot-connected-service#6] opened 2016-04-27 13:57 UTC
ARM based projects (UPW app compiled for Windows 10 IoT Core running on Raspberry Pi) now stop compiling when using the tool's Add -> Connected Service -> IoT Hub.

Error:
Error       File C:\Users\xxx\Documents\Visual Studio 2015\Projects\Tests\Win10IoT Thermo IoTSuite\Win10IoT Thermo\obj\ARM\Debug\Validation\en\Validation.Strings.resw not found.   Win10IoT Thermo C:\Users\xxx\Documents\Visual Studio 2015\Projects\Tests\Win10IoT Thermo IoTSuite\Win10IoT Thermo\MakePRI       

This used to work fine with the earlier version of this tool.

Workaround:

In AzureIoTHub.cs, switch TransportType from AMQP to Http1
var deviceClient = DeviceClient.CreateFromConnectionString(deviceConnectionString, TransportType.Http1);

Then remove all new references added to the project, except for Newtonsoft.Json>

Remove NuGet package 'Microsoft.Azure.Amqp' version 1.1.1.
Remove NuGet package 'PCLCrypto' version 2.0.147.
Remove NuGet package 'PInvoke.BCrypt' version 0.3.2.
Remove NuGet package 'PInvoke.Kernel32' version 0.3.2.
Remove NuGet package 'PInvoke.NCrypt' version 0.3.2.
Remove NuGet package 'PInvoke.Windows.Core' version 0.3.2.
Remove NuGet package 'Validation' version 2.2.8.

after this, the project compiles again and successfully sends messages (HTTP) to the IoT Hub.

**Comment by arturl** [comment] 2016-05-04 19:18
Hi @TechPreacher ,

Thanks for reporting this issue and sorry about the delay in picking it up!

I cannot reproduce this problem with the default blank app -- I can deploy the app on RPi2 and send messages using the Amqp protocol without any issues.

I did get this warning, which may or may not be related:

> MakePRI : warning 0xdef00522: Resources found for language(s) 'en' but no resources found for default language(s): 'en-US'. Change the default language or qualify resources with the default language. http://go.microsoft.com/fwlink/?LinkId=231899

This warning goes away if I uninstall the Validation NuGet package. Can you try that and see if this issue goes away? If it solved the problem, can you send me a small repro and then I can drill into it deeper. Much appreciated!

**Comment by TechPreacher** [comment] 2016-05-24 07:03
Thanks! Delay here as well :)
If I take a blank UWP project, add the connected service reference and then compile it for ARM, it does work correctly! I found out that in my reference demo project the culprit seems to be a C++ library I am using that provides support for the DHT11 temperature sensor. (Source code from https://www.hackster.io/porrey/dht11-dht22-temperature-sensor-077790).

**Comment by arturl** [comment] 2016-05-24 16:56
OK, thanks. In that case, there is no defect in this project and I'm closing this issue.

**Closed as completed** 2016-05-24 17:54 UTC
